import React, { useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { AnimatePresence, motion, MotionConfig, useReducedMotion } from 'framer-motion';
import { ArrowUpRight, ArrowLeft, ArrowRight, Github, X, Crosshair, Cpu, Code2, Wrench, MoveUpRight, Volume2, VolumeX } from 'lucide-react';
import './style.css';
import { AcademicArc, PlusOne } from './AcademicArc.jsx';
import { startAudio, stopAudio, setTrack, setMusicVolume, playSfx } from './audio.js';

const github='https://github.com/Akhil30456';
const sections=['ABOUT ME','PROJECTS','SKILLS','EXPERIENCE','ACADEMIC ARC','+1','CONTACT'];
const routes=['about','projects','skills','experience','academic','plus-one','contact'];
const projects=[
 {name:'ISS LIVE TRACKER',short:'FOLLOW THE ORBIT.',status:'PROTOTYPE',type:'SOFTWARE / SPACE',stack:['React','Three.js','React Three Fiber'],mark:'01',description:'A live view of the International Space Station, plotted against a 3D Earth. An experiment in making orbital data feel tangible.',details:['Interactive Earth with orbit controls','Position marker and orbit trail','A meeting point for space, data, and the web'],note:'Built locally. Public source and a hosted demo are not linked yet.'},
 {name:'ESP32 QUADCOPTER',short:'A WORK IN PROGRESS.',status:'IN PROGRESS',type:'HARDWARE / EXPLORATION',stack:['ESP32','MPU6050','Python'],mark:'02',description:'An ongoing electronics project exploring sensor readings, orientation, and the connection between physical hardware and software.',details:['MPU6050 sensor experiments','Pitch and roll visualization','Learning through calibration and iteration'],note:'An ongoing project, not a finished flight demonstration. Public source is not linked yet.'},
 {name:'ARDUINO MUSIC DISPLAY',short:'GIVE MUSIC A SCREEN.',status:'BUILT',type:'HARDWARE / MUSIC',stack:['Arduino','Python','ST7735'],mark:'03',description:'A tiny desk display for what is playing on the Mac. Album artwork, track information, playback state, and a progress bar, sent over serial.',details:['Live track and artist information','Album art on a 128 × 160 TFT screen','Python-to-Arduino serial communication'],url:github+'/YoutubeMusic-Media-player',note:'A physical hardware project. See the repository for the Python script and Arduino sketch.'},
 {name:'GESTURE AI INTERFACE',short:'HANDS ON. CURSOR OFF.',status:'EXPERIMENT',type:'SOFTWARE / INTERACTION',stack:['Python','Gemini API','Computer vision'],mark:'04',description:'An experimental interface exploring hand gestures and AI interaction, including pinch movement and zoom.',details:['Gesture-driven interaction experiments','Pinch and zoom controls','Exploring a more physical way to use software'],note:'An experimental local build. Public source and a hosted demo are not linked yet.'}
];
const abilities={SOFTWARE:{icon:Code2,desc:'From a small script to an interactive world.',items:[['JavaScript','Browser logic and interactive experiences.'],['React','Component-based interfaces and application state.'],['Python','Hardware bridges, experiments, and small utilities.'],['Three.js','3D scenes, orbital views, and spatial interaction.']]},HARDWARE:{icon:Cpu,desc:'Ideas that leave the screen.',items:[['ESP32','Microcontroller experiments and sensor connections.'],['Arduino','Physical interfaces and the music display.'],['MPU6050','Motion readings and orientation visualization.'],['Sensors','Reading and understanding the physical world.'],['Embedded systems','Exploring the conversation between code and hardware.']]},TOOLS:{icon:Wrench,desc:'The everyday kit for making things happen.',items:[['Git','Tracking changes as a project evolves.'],['GitHub','Sharing code and documenting experiments.'],['VS Code','Writing, exploring, and debugging code.']]}};
const timeline=[['01','3D ON THE WEB','ISS Live Tracker','Exploring React and Three.js through a globe, a moving position marker, and an orbit trail.'],['02','CODE MEETS HARDWARE','Arduino Music Display','Bringing now-playing data out of the laptop and onto a small TFT screen.'],['03','READING MOVEMENT','MPU6050 Visualizer','Connecting an ESP32 and motion sensor to a Python visualization.'],['04','NEXT CHAPTER','Keep experimenting','More interactive experiences. More electronics. More ideas made real.']];
function External({href,children,className=''}){return <a className={className} href={href} target="_blank" rel="noreferrer">{children}<ArrowUpRight size={19}/></a>}
function Stamp({children,className=''}){return <span className={'stamp '+className}>{children}</span>}
function Heading({num,kicker,children}){return <div className="section-heading"><span className="eyebrow">FILE {num} / {kicker}</span><h1>{children}<span className="heading-star" aria-hidden="true">✳</span></h1></div>}
function Cursor(){const ref=useRef(null);useEffect(()=>{const move=e=>{if(ref.current){ref.current.style.transform=`translate3d(${e.clientX}px,${e.clientY}px,0)`;ref.current.classList.toggle('target',!!e.target.closest('button,a'));}};window.addEventListener('pointermove',move);return()=>window.removeEventListener('pointermove',move)},[]);return <div ref={ref} className="cursor" aria-hidden="true"><i/><b/></div>}
function Intro({done}){useEffect(()=>{const t=setTimeout(done,2250);return()=>clearTimeout(t)},[done]);return <motion.div className="intro" exit={{y:'-110%',skewY:-5}} transition={{duration:.35,ease:[.8,0,.2,1]}}><motion.div className="intro-cut" initial={{x:'-110%'}} animate={{x:0}} transition={{delay:.2,duration:.2}}/><motion.div initial={{opacity:0,x:-100}} animate={{opacity:1,x:0}} transition={{delay:.5,duration:.2}}><span className="eyebrow">PLAYER 01 / ENTERING THE WORLD</span><h1>AKHILARYAN<span>!</span></h1><p>Developer • Builder • Electronics Tinkerer</p><small>I build things because wondering if I can is apparently not enough.</small></motion.div><button className="intro-skip" onClick={done}>SKIP INTRO ↗</button></motion.div>}
function Home({go,selected,setSelected}){return <div className="home"><div className="home-left"><span className="eyebrow white-label">PLAYER 01 — PERSONAL FILE</span><div className="name-wrap"><span className="little-note">never stop making.</span><h1>AKHIL<span>ARYAN<span className="red-dot">.</span></span></h1><span className="name-echo" aria-hidden="true">AKHILARYAN</span></div><div className="role-label">DEVELOPER <span>✳</span> BUILDER <span>✳</span><br/>ELECTRONICS TINKERER</div><p className="home-quote">“I build things because wondering<br className="desktop"/> if I can is apparently not enough.”</p><div className="home-bottom"><span className="scribble">curiosity → code → repeat</span><External href={github} className="github-mini"><Github size={17}/> GITHUB</External></div></div><div className="menu-side"><div className="menu-caption"><span>CHOOSE YOUR CHAPTER</span><span>↙</span></div><div className="menu-shell"><div className="menu-inner"><div className="menu-title"><Crosshair size={19}/><span>CHARACTER MENU</span><span>VOL. 01</span></div><nav className="giant-menu" aria-label="Main navigation">{sections.map((s,i)=><motion.button key={s} onMouseEnter={()=>{setSelected(i);playSfx('select')}} onFocus={()=>setSelected(i)} onClick={()=>go(routes[i])} className={selected===i?'selected':''} whileTap={{x:8,rotate:-1}}><span className="menu-number">0{i+1}</span><span className="menu-text">{s}</span><ArrowUpRight className="menu-arrow"/><span className="menu-burst" aria-hidden="true">✦</span></motion.button>)}</nav><div className="menu-instructions"><span>↑ ↓ SELECT</span><span>↵ ENTER</span><span>ESC RETURN</span></div></div></div><div className="menu-sticker">A WORK IN<br/><strong>PROGRESS.</strong><span>AND THAT'S THE POINT.</span></div><span className="orbit-star" aria-hidden="true">✳</span></div></div>}
function About(){return <section className="view about-view"><Heading num="01" kicker="CHARACTER DOSSIER">ABOUT ME</Heading><div className="profile-layout"><div className="profile-art"><div className="portrait-space"><span className="eyebrow">PORTRAIT / UNASSIGNED</span><strong>A<span>!</span></strong><span className="portrait-caption">AKHILARYAN<br/>PLAYER 01</span></div><Stamp>ALWAYS CURIOUS</Stamp><span className="scribble">a little bit of everything.</span></div><div className="bio"><span className="eyebrow">CLASS / DEVELOPER + MAKER</span><h2>IDEAS ARE<br/>BETTER <em>BUILT.</em></h2><p>I'm Akhilaryan. A student developer, maker, and electronics enthusiast.</p><p>I like building software, experimenting with electronics, creating interactive experiences, and turning random ideas into actual projects.</p><div className="bio-facts"><div><span>BASED IN</span><strong>Hyderabad, India</strong></div><div><span>CURRENT FOCUS</span><strong>Code × physical hardware</strong></div></div><div className="interests"><Stamp>SPACE</Stamp><Stamp>ELECTRONICS</Stamp><Stamp>INTERACTIVE WEB</Stamp><Stamp>CARS</Stamp></div><External href={github} className="action white"><Github size={19}/> FIND ME ON GITHUB</External><a className="arc-link" href="#academic">READ THE MESSY STUDY ARC <ArrowUpRight size={19}/></a></div></div></section>}
function ProjectDialog({project,close}){const ref=useRef(null);useEffect(()=>{ref.current.showModal();const d=ref.current;const y=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=y;if(d.open)d.close()}},[]);return <dialog ref={ref} className="project-dialog" aria-labelledby="project-title" onCancel={close} onClick={e=>{if(e.target===ref.current)close()}}><motion.div className="detail-content" initial={{x:100,rotate:3}} animate={{x:0,rotate:0}} transition={{duration:.25}}><button onClick={close} className="close" aria-label="Close project details"><X/></button><span className="eyebrow">MISSION {project.mark} / {project.type}</span><Stamp>{project.status}</Stamp><h2 id="project-title">{project.name}</h2><p className="project-tagline">{project.short}</p><p>{project.description}</p><div className="tech-list">{project.stack.map(t=><span key={t}>{t}</span>)}</div><h3>INSIDE THE BUILD</h3><ul>{project.details.map(d=><li key={d}>{d}</li>)}</ul><div className="project-actions">{project.url?<External className="action dark" href={project.url}><Github size={18}/> GITHUB</External>:<button className="action disabled" disabled>GITHUB — NOT LINKED</button>}<button className="action disabled" disabled>LIVE DEMO — NOT LINKED</button></div><p className="project-note">{project.note}</p></motion.div></dialog>}
function Projects(){const [selected,setSelected]=useState(null);return <section className="view projects-view"><Heading num="02" kicker="MISSION SELECT">THE BUILDS</Heading><div className="project-list">{projects.map((p,i)=><motion.button className={'mission mission-'+i} key={p.name} onClick={()=>setSelected(p)} initial={{x:50,opacity:0}} animate={{x:0,opacity:1}} transition={{delay:i*.07,duration:.22}}><span className="mission-id">/{p.mark}</span><div className="mission-body"><div className="mission-meta"><span>{p.type}</span><span>{p.status}</span></div><h2>{p.name}</h2><div className="mission-reveal"><p>{p.description}</p><div className="tech-list">{p.stack.map(s=><span key={s}>{s}</span>)}</div></div></div><ArrowUpRight className="mission-arrow"/></motion.button>)}</div><div className="project-footer"><span className="scribble">built out of curiosity.</span><span className="eyebrow">SELECT A MISSION TO OPEN ITS FILE ↗</span></div>{selected&&<ProjectDialog project={selected} close={()=>setSelected(null)}/>}</section>}
function Skills(){const [chosen,setChosen]=useState(['JavaScript',abilities.SOFTWARE.items[0][1]]);return <section className="view skills-view"><Heading num="03" kicker="ABILITY LOADOUT">THE TOOLKIT</Heading><div className="skills-grid">{Object.entries(abilities).map(([cat,data],i)=><motion.div className="ability-sheet" key={cat} initial={{y:60,rotate:i%2?3:-3,opacity:0}} animate={{y:0,rotate:i%2?2:-2,opacity:1}} transition={{delay:i*.1,duration:.25}}><div className="ability-top"><data.icon size={30}/><span>CLASS 0{i+1}</span></div><h2>{cat}</h2><p>{data.desc}</p><div className="ability-buttons">{data.items.map(item=><button key={item[0]} className={chosen[0]===item[0]?'active':''} onClick={()=>setChosen(item)}><span>✦</span>{item[0]}<ArrowUpRight size={17}/></button>)}</div></motion.div>)}</div><AnimatePresence mode="wait"><motion.div key={chosen[0]} className="ability-detail" initial={{x:-15,opacity:0}} animate={{x:0,opacity:1}} exit={{opacity:0}} transition={{duration:.15}}><span className="eyebrow">ABILITY SELECTED</span><h3>{chosen[0]}</h3><p>{chosen[1]}</p><span className="ability-spark" aria-hidden="true">✳</span></motion.div></AnimatePresence></section>}
function Experience(){return <section className="view experience-view"><Heading num="04" kicker="PERSONAL BUILD LOG">THE STORY<br/>SO FAR</Heading><p className="timeline-intro">A trail of experiments. Learning by making things.</p><div className="timeline">{timeline.map((t,i)=><motion.article className="timeline-entry" key={t[0]} initial={{x:i%2?70:-70,opacity:0}} whileInView={{x:0,opacity:1}} viewport={{once:true,amount:.3}} transition={{duration:.3}}><span className="timeline-index">{t[0]}</span><span className="timeline-year" aria-hidden="true">{i===3?'NEXT':'2026'}</span><div className="timeline-text"><span className="eyebrow">{i===3?'ONGOING':'SEPTEMBER 2026'} / {t[1]}</span><h2>{t[2]}</h2><p>{t[3]}</p></div></motion.article>)}</div><a className="arc-link" href="#academic">NEXT FILE: ACADEMIC ARC <ArrowUpRight size={19}/></a></section>}
function Contact(){const [open,setOpen]=useState(false);return <section className="view contact-view"><span className="eyebrow">FILE 07 / OPEN A CONVERSATION</span><div className="dialogue"><h1>WHAT SHOULD<br/>WE <span>BUILD?</span></h1><span className="dialogue-tail"/></div><p>Got an idea? Let's see where it goes.</p><button className="contact-button" aria-expanded={open} onClick={()=>setOpen(!open)}>CONTACT <ArrowUpRight/></button><AnimatePresence>{open&&<motion.div className="contact-options" initial={{height:0,opacity:0}} animate={{height:'auto',opacity:1}} exit={{height:0,opacity:0}}><p>Find my projects and profile on GitHub.</p><External href={github}><Github size={19}/> Akhil30456</External><span>Email and Instagram haven't been linked yet.</span></motion.div>}</AnimatePresence><div className="contact-links"><External href={github}>GITHUB</External><span>EMAIL <small>NOT LINKED</small></span><span>INSTAGRAM <small>NOT LINKED</small></span></div><span className="contact-signature">Akhilaryan.</span></section>}
function MusicControl(){const [enabled,setEnabled]=useState(false),[volume,setVolume]=useState(55);useEffect(()=>()=>stopAudio(),[]);const toggle=async()=>{if(enabled){stopAudio();setEnabled(false)}else{const ok=await startAudio();setEnabled(ok)}};return <div className="music-widget"><button className="music-control" onClick={toggle} aria-pressed={enabled} aria-label={enabled?'Mute game music':'Enable game music'}>{enabled?<Volume2 size={17}/>:<VolumeX size={17}/>}<span>SOUND {enabled?'ON':'OFF'}</span><i className={enabled?'playing':''} aria-hidden="true"/></button>{enabled&&<input aria-label="Music volume" type="range" min="0" max="100" value={volume} onChange={e=>{const v=Number(e.target.value);setVolume(v);setMusicVolume(v/100)}}/>}</div>}
function App(){const valid=()=>routes.includes(location.hash.slice(1))?location.hash.slice(1):'home';const [view,setView]=useState(valid),[intro,setIntro]=useState(!sessionStorage.getItem('akhil-intro')),[selected,setSelected]=useState(0),[motionOff,setMotionOff]=useState(false);const reduced=useReducedMotion();const root=useRef(null),content=useRef(null);const go=v=>{playSfx('confirm');location.hash=v==='home'?'':v;setView(v);window.scrollTo(0,0)};const endIntro=React.useCallback(()=>{setIntro(false);sessionStorage.setItem('akhil-intro','1')},[]);
useEffect(()=>{if(view!=='academic')setTrack(view)},[view]);
useEffect(()=>{const fn=()=>{setView(valid());window.scrollTo(0,0)};window.addEventListener('hashchange',fn);return()=>window.removeEventListener('hashchange',fn)},[]);
useEffect(()=>{const fn=e=>{if(document.querySelector('dialog[open]'))return;if(e.key==='Escape'){endIntro();go('home')}if(intro)return;if(e.target.closest('button')&&e.target.closest('.giant-menu')&&['ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();const next=(selected+(e.key==='ArrowDown'?1:sections.length-1))%sections.length;setSelected(next);document.querySelectorAll('.giant-menu button')[next]?.focus();return}if(e.target.closest('a,button,input,textarea'))return;if(view==='home'){if(e.key==='ArrowDown'){e.preventDefault();setSelected(s=>(s+1)%sections.length)}if(e.key==='ArrowUp'){e.preventDefault();setSelected(s=>(s+sections.length-1)%sections.length)}if(e.key==='Enter')go(routes[selected]);}if(/^[1-7]$/.test(e.key))go(routes[Number(e.key)-1])};window.addEventListener('keydown',fn);return()=>window.removeEventListener('keydown',fn)},[view,selected,intro,endIntro]);
useEffect(()=>{if(reduced)endIntro()},[reduced,endIntro]);
useEffect(()=>{if(!intro&&view!=='home')content.current?.focus({preventScroll:true})},[view,intro]);
const quiet=motionOff||reduced;return <MotionConfig reducedMotion={quiet?'always':'user'}><div ref={root} className={`app view-${view} ${quiet?'motion-off':''}`} onPointerMove={e=>{if(!quiet&&e.pointerType==='mouse'){root.current.style.setProperty('--mx',`${(e.clientX/innerWidth-.5)*12}px`);root.current.style.setProperty('--my',`${(e.clientY/innerHeight-.5)*12}px`)}}}><a className="skip-link" href="#main" onClick={e=>{e.preventDefault();content.current?.focus();content.current?.scrollIntoView()}}>Skip to content</a><div className="environment" aria-hidden="true"><div className="red-plane"/><div className="speed-lines"/><div className="halftone"/><span className="background-type">MAKE<br/>SOMETHING.</span><span className="environment-cross">+</span></div><header><button className="brand" onClick={()=>go('home')} aria-label="Return to character menu">A<span>!</span></button><div className="header-title"><strong>AKHILARYAN</strong><span>PERSONAL PORTFOLIO / VOL. 01</span></div><div className="header-right"><MusicControl/><span className="status-label">INDEPENDENT MIND. OPEN SOURCE.</span><button className="motion-control" onClick={()=>setMotionOff(!motionOff)} aria-pressed={motionOff}>MOTION {quiet?'OFF':'ON'}</button>{view!=='home'&&<button className="back-menu" onClick={()=>go('home')}><ArrowLeft size={16}/> MENU</button>}</div></header>{view!=='home'&&<nav className="section-nav" aria-label="Sections">{sections.map((s,i)=><button key={s} className={view===routes[i]?'active':''} onClick={()=>go(routes[i])}><span>0{i+1}</span> {s}</button>)}</nav>}<main id="main" ref={content} tabIndex={-1}><AnimatePresence mode="wait"><motion.div key={view} initial={{opacity:0,x:quiet?0:35,clipPath:'inset(0 0 0 0)'}} animate={{opacity:1,x:0}} exit={{opacity:0,x:quiet?0:-25}} transition={{duration:quiet?0:.16,ease:[.2,.8,.2,1]}}>{!quiet&&<motion.div aria-hidden="true" className="panel-wipe" initial={{scaleX:1}} animate={{scaleX:0}} transition={{duration:.28,ease:[.8,0,.2,1]}}/>}{view==='home'?<Home go={go} selected={selected} setSelected={setSelected}/>:view==='about'?<About/>:view==='projects'?<Projects/>:view==='skills'?<Skills/>:view==='experience'?<Experience/>:view==='academic'?<AcademicArc onSceneChange={i=>setTrack(`academic-${i}`)} continueToPlus={()=>go('plus-one')}/>:view==='plus-one'?<PlusOne go={go}/>:<Contact/>}</motion.div></AnimatePresence></main><footer><span><b>✳</b> BUILT FROM CURIOSITY</span><span>CODE. BREAK. LEARN. REPEAT.</span><span>AK / 2026 <ArrowUpRight size={14}/></span></footer><Cursor/><AnimatePresence>{intro&&!reduced&&<Intro done={endIntro}/>}</AnimatePresence></div></MotionConfig>}

createRoot(document.getElementById('root')).render(<App/>);
